# -*- coding: utf-8 -*-
"""analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ySa-OjYpcuXzO5g3XUvUg2r7U069ydPt
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the cleaned data
clean_file_path = "/content/clean_frailty_data1.csv"
data = pd.read_csv(clean_file_path)

# Perform EDA (e.g., visualize distributions, correlations, etc.)
# Example:
sns.pairplot(data, hue='Frailty')
plt.show()

import pandas as pd
from scipy.stats import ttest_ind

# Reading the CSV file
file_path = "/content/clean_frailty_data1.csv"
frailty_data = pd.read_csv(file_path)

# Displaying summary statistics of the dataset
print("Summary of the dataset:")
print(frailty_data.describe())

# Converting 'Frailty' column to a categorical variable
frailty_data['Frailty'] = pd.Categorical(frailty_data['Frailty'])

# Performing t-test for comparing weight between frail and non-frail groups
group_frail = frailty_data[frailty_data['Frailty'] == 'Y']['Weight']
group_non_frail = frailty_data[frailty_data['Frailty'] == 'N']['Weight']

# Performing t-test assuming unequal variances between groups
t_statistic, p_value = ttest_ind(group_frail, group_non_frail, equal_var=False)

# Printing t-test results
print("\nT-test Results:")
print("T-statistic:", t_statistic)
print("P-value:", p_value)

# Writing t-test results to a text file
result_file_path = "/content/result/result.txt"
with open(result_file_path, 'w') as file:
    file.write("T-test results for comparing weight between frail and non-frail groups:\n")
    file.write("T-statistic: {}\n".format(t_statistic))
    file.write("P-value: {}\n".format(p_value))
    file.write("Degree of Freedom: {}\n".format(degree_of_freedom))

