# -*- coding: utf-8 -*-
"""prepocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ySa-OjYpcuXzO5g3XUvUg2r7U069ydPt
"""

import pandas as pd

# Reading the CSV file
file_path = "/content/raw_frailty_data1.csv"
frailty_data = pd.read_csv(file_path)

# Getting the summary of the data
print(frailty_data.describe())

# Renaming the columns
frailty_data.columns = ['Height', 'Weight', 'Age', 'Grip_Strength', 'Frailty']

# Understanding the data and dimensions
print(frailty_data.columns)
print(frailty_data.shape)

# Getting the top rows
print(frailty_data.head())

# Getting the data structure
print(frailty_data.info())

# Converting Frailty column to categorical
frailty_data['Frailty'] = pd.Categorical(frailty_data['Frailty'])

# Checking for any missing values
print(frailty_data.isnull().any())

# Writing the cleaned data to a new CSV file
clean_file_path = "clean_frailty_data1.csv"
frailty_data.to_csv(clean_file_path, index=False)



