# -*- coding: utf-8 -*-
"""Q2_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MWQWOe1vMYQDqiu8Ujkocz7j0izLpF3D
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Reading the CSV file
Student = pd.read_csv("/Users/pavanpratapagiri/PDS/PDSAssignment/Assignment-1/Question_2/clean_data/clean_data_file.csv")

# Getting info of complete CSV
print(Student.info())

# Creating a DataFrame
Student_Data = pd.DataFrame(Student)

# Understanding the data and dimensions
print(Student_Data.columns)
print(Student_Data.shape)
print(Student_Data.head())
print(Student_Data.describe())

# Plotting the Graphs - Visualize the data using different techniques

# 1. Plotting the frequency of each category in the "race/ethnicity" feature
plt.figure(figsize=(10, 6))
sns.countplot(y='race/ethnicity', data=Student_Data, palette='viridis')
plt.title('Data Based On Race Ethnicity')
plt.xlabel('Frequency')
plt.ylabel('Race Ethnicity')
plt.show()

# 2.1 Boxplot - Distribution MathScore Based on Sex
plt.figure(figsize=(8, 6))
sns.boxplot(x='gender', y='math score', data=Student_Data, palette='Set2')
plt.title('Distribution MathScore Based on Sex')
plt.xlabel('Gender')
plt.ylabel('Math Score')
plt.show()

# 2.2 and 2.3 Boxplots of Reading and Writing Score vs Gender
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
sns.boxplot(x='gender', y='reading score', data=Student_Data, palette='coolwarm')
plt.title('Boxplots of Reading Score vs Gender')
plt.xlabel('Gender')
plt.ylabel('Reading Score')

plt.subplot(1, 2, 2)
sns.boxplot(x='gender', y='writing score', data=Student_Data, palette='coolwarm')
plt.title('Boxplots of Writing Score vs Gender')
plt.xlabel('Gender')
plt.ylabel('Writing Score')
plt.tight_layout()
plt.show()

# 3. Scatter plot - Correlation Math Score & Reading Score
plt.figure(figsize=(8, 6))
sns.scatterplot(x='math score', y='reading score', hue='gender', data=Student_Data)
plt.title('Correlation Math Score & Reading Score')
plt.xlabel('Math Score')
plt.ylabel('Reading Score')
plt.show()

# 4. Histograms - Distribution of Math, Reading, and Writing Scores
plt.figure(figsize=(12, 8))
plt.subplot(2, 2, 1)
plt.hist(Student_Data['math score'], bins=10, color='skyblue')
plt.title('Distribution Math Score')
plt.xlabel('Math Score')
plt.ylabel('Frequency')

plt.subplot(2, 2, 2)
plt.hist(Student_Data['reading score'], bins=10, color='salmon')
plt.title('Distribution Reading Score')
plt.xlabel('Reading Score')
plt.ylabel('Frequency')

plt.subplot(2, 2, 3)
plt.hist(Student_Data['writing score'], bins=10, color='lightgreen')
plt.title('Distribution Writing Score')
plt.xlabel('Writing Score')
plt.ylabel('Frequency')

plt.tight_layout()
plt.show()

#5. pairplot - Pair Plot of Math, Reading, Writing and Total Scores with Gender
sns.pairplot(Student_Data[['math score', 'reading score', 'writing score', 'Total score', 'gender']], hue='gender')
plt.suptitle('Pair Plot of Scores with Gender', y=1.02)
plt.show()

#6. Pie Plot - Distribution of parental level of education Type
plt.figure(figsize=(8, 8))
labels = Student_Data['parental level of education'].value_counts().index
sizes = Student_Data['parental level of education'].value_counts().values
plt.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=140, colors=['#66b3ff','#99ff99'])
plt.title('Distribution of parental level of education Type')
plt.show()



